clear all
rng(45, 'twister');
nx = 3;
nu = 2;
ny = 3;
nd = 2;

% S = ;

% epsilon list
epsilon_list = [0.01; 0.05; 0.1; 0.15; 0.2; 0.5];

% T = 6;
% T = 10;
% T = 30;
T = 50;


sys = struct(...
    'A', [0.8 0.2  0.1;...
          0.1 0.7 -0.3;...
         -0.3 0.5  0.9],...
    'B', [1 0;...
          0 1;...
          1 1],...
    'G', [0.3 0.1;...
          0.2 0.2;...
          0.1 0.3],...
    'C', [1 0 0;...
          0 1 0;...
          0 0 1],...
    'D', [0.1 0.2;...
          0.3 0.1;...
          0.2 0.1],...
    'H', [0.1 0.1;...
          0.2 0.2;...
          0.3 0.3],...
    'nx',nx,'nu',nu,'ny',ny,'nd',nd);

SIM_list = cell(1,length(epsilon_list)); % 目前还没有用到这个，后面这个要自己设计
SIM = simulator(sys);
for j=1:length(epsilon_list)
    SIM_list{j} = SIM.run(epsilon_list(j),T);
end
%%
hinf_module = Hinf_module_my_unstructured(sys);


%% model-based and data-driven control
sol_table = cell(1,1+length(epsilon_list)); 
hinf_table = NaN*zeros(1,1+length(epsilon_list));
sol_table{1} = hinf_module.model_based_Hinf(); % cell一定要用{}
hinf_table(1) = sol_table{1}.hinf;
for j=1:length(epsilon_list)
    SIM_out = SIM_list{j};
    try
        sol_table{j+1} = hinf_module.data_driven_Hinf(SIM_out);
        hinf_table(j+1) = sol_table{j+1}.hinf;
    catch
        sol_table{j+1} = NaN;
    end
end